from pathlib import Path
import argparse, numpy as np, pandas as pd
IEA_GWP=35.8; IEA_YIELD=976.0; IEA_RD=0.7; PANEL_LIFE=30; INVERTER_LIFE=15; HORIZON=30
SHARE_MODULE=.56; SHARE_INVERTER=.28; SHARE_OTHER=.16

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--lifetime',required=True); ap.add_argument('--out',default='processed/06_LCA_GWP'); args=ap.parse_args(); out=Path(args.out); out.mkdir(parents=True,exist_ok=True)
    df=pd.read_csv(args.lifetime,low_memory=False)
    rd=IEA_RD/100; iea_gen=sum(IEA_YIELD*(1-rd*(y-1)) for y in range(1,PANEL_LIFE+1)); total=IEA_GWP*iea_gen/1000; mod=total*SHARE_MODULE; inv=total*SHARE_INVERTER; other=total*SHARE_OTHER; inv_units=int(np.ceil(HORIZON/INVERTER_LIFE))
    pd.DataFrame({'parameter':['IEA_GWP_gCO2eq_per_kWh','IEA_annual_yield_kWh_per_kWp','IEA_linear_degradation_pct_per_year','IEA_panel_life_years','IEA_inverter_life_years','IEA_reference_lifetime_generation_kWh_per_kWp','IEA_total_GWP_kgCO2eq_per_kWp','module_share','inverter_share','other_share','module_GWP_kgCO2eq_per_kWp','inverter_GWP_30y_kgCO2eq_per_kWp','other_GWP_kgCO2eq_per_kWp','inverter_units_30y'],'value':[IEA_GWP,IEA_YIELD,IEA_RD,PANEL_LIFE,INVERTER_LIFE,iea_gen,total,SHARE_MODULE,SHARE_INVERTER,SHARE_OTHER,mod,inv,other,inv_units]}).to_csv(out/'IEA_REFERENCE_GWP_RECONSTRUCTION.csv',index=False)
    r=df.copy(); r['module_GWP_kgCO2eq']=r.module_units_required_30y*mod; r['inverter_units_30y']=inv_units; r['inverter_GWP_kgCO2eq']=inv; r['other_GWP_kgCO2eq']=other; r['total_GWP_kgCO2eq_30y']=r.module_GWP_kgCO2eq+inv+other; r['GWP_gCO2eq_per_kWh']=r.total_GWP_kgCO2eq_30y*1000/r.system30_generation_with_replacements_kWh_per_kWp; r['GWP_kgCO2eq_per_kWh']=r.GWP_gCO2eq_per_kWh/1000; r['module_equiv_residual']=np.maximum(1,HORIZON/r.service_life_years); r['residual_module_GWP_kgCO2eq']=r.module_equiv_residual*mod; r['residual_total_GWP_kgCO2eq_30y']=r.residual_module_GWP_kgCO2eq+inv+other; r['residual_GWP_gCO2eq_per_kWh']=r.residual_total_GWP_kgCO2eq_30y*1000/r.system30_generation_with_replacements_kWh_per_kWp
    for name,kg in [('module',r.module_GWP_kgCO2eq),('inverter',r.inverter_GWP_kgCO2eq),('other',r.other_GWP_kgCO2eq)]: r[f'{name}_GWP_gCO2eq_per_kWh']=kg*1000/r.system30_generation_with_replacements_kWh_per_kWp; r[f'{name}_contribution_pct']=kg/r.total_GWP_kgCO2eq_30y*100
    r['counterfactual_no_replacement_total_GWP_kg']=total; r['counterfactual_no_replacement_GWP_g_per_kWh']=total*1000/r.fixed30_no_replacement_generation_kWh_per_kWp; r['replacement_effect_on_GWP_g_per_kWh']=r.GWP_gCO2eq_per_kWh-r.counterfactual_no_replacement_GWP_g_per_kWh; r['additional_module_units_due_to_climate']=r.module_units_required_30y-1; r['additional_module_GWP_kgCO2eq']=r.additional_module_units_due_to_climate*mod; r['replacement_burden_share_of_total_GWP_pct']=r.additional_module_GWP_kgCO2eq/r.total_GWP_kgCO2eq_30y*100; r.to_csv(out/'LCA_GWP_PERIOD_SUMMARY.csv',index=False)
    ch=[]
    for m in r.model.unique():
        h=r[(r.model==m)&(r.scenario=='historical')].iloc[0]
        for _,x in r[(r.model==m)&(r.scenario!='historical')].iterrows(): ch.append({'model':m,'scenario':x.scenario,'period':x.period,'historical_GWP_gCO2eq_per_kWh':h.GWP_gCO2eq_per_kWh,'future_GWP_gCO2eq_per_kWh':x.GWP_gCO2eq_per_kWh,'GWP_change_gCO2eq_per_kWh':x.GWP_gCO2eq_per_kWh-h.GWP_gCO2eq_per_kWh,'GWP_change_pct':(x.GWP_gCO2eq_per_kWh/h.GWP_gCO2eq_per_kWh-1)*100,'historical_module_units_30y':h.module_units_required_30y,'future_module_units_30y':x.module_units_required_30y,'additional_module_units':x.module_units_required_30y-h.module_units_required_30y,'replacement_effect_on_GWP_g_per_kWh':x.replacement_effect_on_GWP_g_per_kWh})
    pd.DataFrame(ch).to_csv(out/'LCA_GWP_CHANGE_FROM_HISTORICAL.csv',index=False)
    ens=r.groupby(['scenario','period']).agg(GWP_gCO2eq_per_kWh_mean=('GWP_gCO2eq_per_kWh','mean'),GWP_gCO2eq_per_kWh_std=('GWP_gCO2eq_per_kWh','std'),GWP_gCO2eq_per_kWh_min=('GWP_gCO2eq_per_kWh','min'),GWP_gCO2eq_per_kWh_max=('GWP_gCO2eq_per_kWh','max'),total_GWP_kgCO2eq_mean=('total_GWP_kgCO2eq_30y','mean'),module_GWP_g_per_kWh_mean=('module_GWP_gCO2eq_per_kWh','mean'),inverter_GWP_g_per_kWh_mean=('inverter_GWP_gCO2eq_per_kWh','mean'),other_GWP_g_per_kWh_mean=('other_GWP_gCO2eq_per_kWh','mean'),module_units_30y_mean=('module_units_required_30y','mean'),service_life_years_mean=('service_life_years','mean'),generation_30y_kWh_per_kWp_mean=('system30_generation_with_replacements_kWh_per_kWp','mean'),counterfactual_no_replacement_GWP_mean=('counterfactual_no_replacement_GWP_g_per_kWh','mean'),replacement_effect_GWP_mean=('replacement_effect_on_GWP_g_per_kWh','mean'),residual_GWP_gCO2eq_per_kWh_mean=('residual_GWP_gCO2eq_per_kWh','mean')).reset_index(); h=ens[ens.scenario=='historical'];
    if len(h)==1:
        hg=float(h.iloc[0].GWP_gCO2eq_per_kWh_mean); ens['GWP_change_vs_historical_pct']=(ens.GWP_gCO2eq_per_kWh_mean/hg-1)*100; ens['GWP_change_vs_historical_g_per_kWh']=ens.GWP_gCO2eq_per_kWh_mean-hg
    ens.to_csv(out/'LCA_GWP_ENSEMBLE_SUMMARY.csv',index=False)
    r[['model','scenario','period','module_units_required_30y','module_GWP_kgCO2eq','inverter_GWP_kgCO2eq','other_GWP_kgCO2eq','total_GWP_kgCO2eq_30y','module_GWP_gCO2eq_per_kWh','inverter_GWP_gCO2eq_per_kWh','other_GWP_gCO2eq_per_kWh','module_contribution_pct','inverter_contribution_pct','other_contribution_pct','additional_module_GWP_kgCO2eq','replacement_burden_share_of_total_GWP_pct']].to_csv(out/'LCA_GWP_CONTRIBUTIONS.csv',index=False)
    sens=[]
    for _,x in r.iterrows(): sens.extend([{'model':x.model,'scenario':x.scenario,'period':x.period,'case':'Main_with_service_life_replacement','module_units_30y':x.module_units_required_30y,'GWP_gCO2eq_per_kWh':x.GWP_gCO2eq_per_kWh},{'model':x.model,'scenario':x.scenario,'period':x.period,'case':'Counterfactual_no_module_replacement','module_units_30y':1,'GWP_gCO2eq_per_kWh':x.counterfactual_no_replacement_GWP_g_per_kWh}])
    pd.DataFrame(sens).to_csv(out/'LCA_GWP_REPLACEMENT_SENSITIVITY.csv',index=False)
    pd.DataFrame({'item':['input_scenario_rows','missing_generation_values','missing_service_life_values','contribution_share_sum','IEA_reference_GWP_gCO2eq_per_kWh','IEA_reference_lifetime_generation_kWh_per_kWp','IEA_reconstructed_total_burden_kgCO2eq_per_kWp','minimum_module_units_30y','maximum_module_units_30y','minimum_GWP_gCO2eq_per_kWh','maximum_GWP_gCO2eq_per_kWh'],'value':[len(r),r.system30_generation_with_replacements_kWh_per_kWp.isna().sum(),r.service_life_years.isna().sum(),SHARE_MODULE+SHARE_INVERTER+SHARE_OTHER,IEA_GWP,iea_gen,total,r.module_units_required_30y.min(),r.module_units_required_30y.max(),r.GWP_gCO2eq_per_kWh.min(),r.GWP_gCO2eq_per_kWh.max()]}).to_csv(out/'LCA_GWP_QC_SUMMARY.csv',index=False)
    (out/'LCA_GWP_METHOD_AND_ASSUMPTIONS.txt').write_text('Scenario-adjusted attributional GWP anchored to the published IEA-PVPS characterized mono-Si rooftop reference: 35.8 g CO2-eq/kWh, 976 kWh/kWp/yr, 0.7%/yr degradation, 30-y panel life, 15-y inverter life. GWP shares: module 56%, inverter 28%, other 16%. Module burden is multiplied by integer module units required in the fixed 30-y horizon. This integer replacement creates a step change and should be complemented by an annualized/allocation sensitivity for high-tier publication.')
    print('Done:',out)

if __name__=='__main__': main()
